FramesPanel=function(){this.thumbSize=65;this.title='TIMELINE';this.titleDOM;this.panelMenu;this.frameTools;this.minimap;this.viewfinder;this.player={fps:12,play:!1,loop:{},timeStamp:new Date().getTime(),frame:1,sprite:{}}}
FramesPanel.prototype.init=function(){let panel=new Component('panel','panel-frames');panel.appendTo('#app-main');let preview=new Component('panel','frames-preview');preview.setHeight('4');preview.appendTo(panel);let titleBar=new Component('titleBar');titleBar.setHeight('4');titleBar.addTitle('PREVIEW');titleBar.appendTo(preview);titleBar.addGizmo('numberDrag','set-fps',12,'FPS',setFPS.bind(this));titleBar.gizmo['set-fps'].setFormat(0,60);function setFPS(val){this.player.fps=val;if(this.player.fps==0)this.player.play=!1;else this.player.play=!0}
let minimap=new Component('subPanel','frames-minimap');minimap.appendTo(preview);this.createMinimap(minimap.DOM);this.updateViewfinder(0,0,0,0);let mainPanel=new Component('panel','frames-mainpanel');mainPanel.appendTo(panel);this.panelMenu=new Component('topMenu');this.panelMenu.appendTo(mainPanel);let timeline=new Component('subPanel','frames-timeline');timeline.appendTo(mainPanel);timeline.setHeight('3');this.panelMenu.addButton('tab','frames-preview','mdi-movie').toggleMenu(!0);this.panelMenu.addButton('tab','frames-timeline','mdi-animation').toggleMenu(!0);this.panelMenu.addButton('function','frames-onionskin','mdi-checkbox-multiple-blank-circle-outline').toggle();this.titleDOM=new Component('titleBarThin');this.titleDOM.addTitle(this.title);this.titleDOM.appendTo(timeline);this.titleDOM.addGizmo('numberDrag','set-onionskin','-1','ONIONSKIN');let frameBox=new Component('contentBox','frames-thumbs');frameBox.setHeight('2');frameBox.appendTo(timeline);this.frameTools=new Component('bottomMenu','frames-control');this.frameTools.appendTo(timeline);this.frameTools.setHeight('1');this.frameTools.addButton('function','frames-add','mdi-plus');this.frameTools.addButton('function','frames-left','mdi-arrow-left');this.frameTools.addButton('function','frames-right','mdi-arrow-right');this.frameTools.addButton('function','frames-duplicate','mdi-content-duplicate');this.frameTools.addButton('function','frames-delete','mdi-delete');this.frameTools.addButton('cta','frames-export','EXPORT');panel.activateGizmos()}
FramesPanel.prototype.getPanelHeight=function(){let timeline=document.getElementById('frames-timeline'),height=timeline.offsetHeight||0;if(timeline.style.display=='none')height=0;return height}
FramesPanel.prototype.createMinimap=function(parent){this.minimap=document.createElement('canvas');this.minimap.id="minimap";this.minimap.width=parent.offsetWidth;this.minimap.height=parent.offsetWidth;this.minimap.getContext('2d').imageSmoothingEnabled=!1;parent.appendChild(this.minimap);let playPause=document.createElement('div'),content=document.createElement('span');playPause.className='player';content.className='mdi mdi-play';playPause.appendChild(content);parent.appendChild(playPause);parent.addEventListener('click',playToggle.bind(this),!1);function playToggle(){if(this.player.play){this.player.play=!1;content.className='mdi mdi-pause';playPause.className='player pause'}
else{this.player.play=!0;content.className='mdi mdi-play';playPause.className='player play'}}}
FramesPanel.prototype.updateMinimap=function(spriteFrameData,animation){let map=this.minimap.getContext('2d'),mw=this.minimap.width,mh=this.minimap.height;if(!this.player.play||animation){map.clearRect(0,0,mw,mh);map.imageSmoothingEnabled=!1;let mixdown=spriteFrameData.mixdown;map.drawImage(mixdown,0,0,mixdown.width,mixdown.height,0,0,mw,mh)}
map.imageSmoothingEnabled=!0;map.strokeStyle="#f00";map.lineWidth=2;let view=this.viewfinder;map.strokeRect(view.vx,view.vy,view.vw,view.vh)}
FramesPanel.prototype.updateViewfinder=function(vx,vy,vw,vh){this.viewfinder={vx:vx,vy:vy,vw:vw,vh:vh}}
FramesPanel.prototype.addThumb=function(frameNum,clickFn){let thumbs=document.getElementsByClassName('frameThumb');for(let j=0;j<thumbs.length;j++){thumbs[j].removeAttribute('data-active');let fnum=parseInt(thumbs[j].getAttribute('data-frame-num'));if(fnum>=frameNum){fnum++;thumbs[j].setAttribute('data-frame-num',fnum);thumbs[j].style.order=fnum;thumbs[j].childNodes[1].innerHTML=fnum}}
let parent=document.getElementById('frames-thumbs'),thumb=document.createElement('div'),thumbImage=document.createElement('canvas'),thumbNum=document.createElement('div');thumb.setAttribute('data-frame-num',frameNum);thumb.className='frameThumb';thumb.style.order=frameNum;thumb.style.width=this.thumbSize+'px';thumb.style.height=this.thumbSize+'px';parent.appendChild(thumb);thumbImage.width=this.thumbSize;thumbImage.height=this.thumbSize;thumbImage.getContext('2d').imageSmoothingEnabled=!1;thumb.appendChild(thumbImage);thumbNum.className='fnumber';thumbNum.innerHTML=frameNum;thumb.appendChild(thumbNum);thumb.setAttribute('data-active','');this.titleDOM.title.DOM.innerHTML=this.title+' ('+frameNum+'/'+thumbs.length+')';thumb.addEventListener('click',selectThumb.bind(this),!1);function selectThumb(e){let fnum=thumb.getAttribute('data-frame-num');this.selectThumb(fnum);clickFn(fnum)}}
FramesPanel.prototype.selectThumb=function(frameNum){let tmbs=document.getElementsByClassName('frameThumb');for(let j=0;j<tmbs.length;j++){let fnum=tmbs[j].getAttribute('data-frame-num');if(fnum==frameNum){tmbs[j].setAttribute('data-active','')}
else{tmbs[j].removeAttribute('data-active')}}
this.titleDOM.title.DOM.innerHTML=this.title+' ('+frameNum+'/'+tmbs.length+')'}
FramesPanel.prototype.updateThumb=function(spriteFrameData){let thumbData=spriteFrameData.mixdown,thumbs=document.getElementsByClassName('frameThumb');for(var i=0;i<thumbs.length;i++){let thumb=thumbs[i],thumbImage=thumb.firstChild,num=thumb.getAttribute('data-frame-num');if(num==spriteFrameData.num){let thumbCtx=thumbImage.getContext('2d');thumbCtx.clearRect(0,0,thumbImage.width,thumbImage.height);thumbCtx.drawImage(thumbData,0,0,thumbData.width,thumbData.height,0,0,thumbImage.width,thumbImage.height);break}}}
FramesPanel.prototype.updateAllThumbs=function(spriteFrameDataAll){let frameData=spriteFrameDataAll,thumbs=document.getElementsByClassName('frameThumb');for(var f=0;f<frameData.length;f++){let frame=frameData[f],mixdown=frame.mixdown,thumb=thumbs[f],thumbImage=thumb.firstChild,thumbNum=thumb.childNodes[1];thumbNum.innerHTML=frame.num;thumb.setAttribute('data-frame-num',frame.num);thumb.style.order=frame.num;let thumbCtx=thumbImage.getContext('2d');thumbCtx.clearRect(0,0,thumbImage.width,thumbImage.height);thumbCtx.drawImage(mixdown,0,0,mixdown.width,mixdown.height,0,0,thumbImage.width,thumbImage.height)}}
FramesPanel.prototype.playPreview=function(sprite){this.player.play=!0;this.player.sprite=sprite;var _this=this;(function animInterval(){var interval=1000/_this.player.fps,now=new Date().getTime(),delta=now-_this.player.timeStamp;if(delta>interval){_this.player.timeStamp=now-(delta%interval);if(_this.player.play)_this.playFrame()}
_this.player.loop=requestAnimationFrame(animInterval)})()}
FramesPanel.prototype.stopPreview=function(sprite){this.player.play=!1;this.player.frame=1}
FramesPanel.prototype.playFrame=function(){let sprite=this.player.sprite,amount=sprite.frameData.length,fnum=this.player.frame,frameData=sprite.getFrameData(fnum);this.updateMinimap(frameData,!0);if(parseInt(fnum)==amount)this.player.frame=1;else this.player.frame++}
FramesPanel.prototype.removeAllThumbs=function(){let parent=document.getElementById('frames-thumbs');while(parent.firstChild){parent.removeChild(parent.firstChild)}}
FramesPanel.prototype.removeThumb=function(frameNum){let thumbs=document.getElementsByClassName('frameThumb'),parent=document.getElementById('frames-thumbs');if(thumbs.length==1)return;for(let i=0;i<thumbs.length;i++){let tmb=thumbs[i],fnum=parseInt(tmb.getAttribute('data-frame-num'));if(fnum==frameNum){parent.removeChild(thumbs[i])}}
for(let i=0;i<thumbs.length;i++){let tmb=thumbs[i],fnum=parseInt(tmb.getAttribute('data-frame-num'));if(fnum>frameNum){fnum--;tmb.setAttribute('data-frame-num',fnum);tmb.style.order=fnum;tmb.childNodes[1].innerHTML=fnum}
if(fnum==frameNum){tmb.setAttribute('data-active','')}
if(frameNum==thumbs.length+1){if(fnum==thumbs.length){tmb.setAttribute('data-active','');frameNum=fnum}}}
this.titleDOM.title.innerHTML=this.title+' ('+frameNum+'/'+thumbs.length+')';this.player.frame=1}