var LayersPanel=function(){this.thumbSize=35;this.thumb;this.title='LAYERS';this.panel;this.card={};this.panelMenu;this.layerTools;this.artboardTools;this.artboard={anchor:[0,0],aspectLock:!0,width:32,height:32,ui:{},update:this.updateArtboardPanel}
this.settings={showGrid:!0,showGuides:!0,background:'light'}}
LayersPanel.prototype.init=function(){this.panel=new Component('panel','panel-layers');this.panel.appendTo('#workspace');this.panelMenu=new Component('topMenu');this.panelMenu.appendTo(this.panel);let layersMain=new Component('subPanel','layers-thumbs');layersMain.appendTo(this.panel);layersMain.setHeight('3');let titleBar=new Component('titleBarThin');titleBar.addTitle('LAYERS');titleBar.appendTo(layersMain);let artboardMain=new Component('subPanel','layers-artboard');artboardMain.appendTo(this.panel);artboardMain.setHeight('3');titleBar=new Component('titleBarThin');titleBar.addTitle('ARTBOARD');titleBar.appendTo(artboardMain);this.initArtboardPanel(artboardMain);this.panelMenu.addButton('tab','layers-thumbs','mdi-layers').toggleMenu(!0).radio('l1',!0);this.panelMenu.addButton('tab','layers-artboard','mdi-image').toggleMenu(!1).radio('l1',!0);this.panelMenu.addButton('function','file-menu','mdi-menu');let layerThumbs=new Component('contentBox','layers-cards');layerThumbs.setHeight('2');layerThumbs.appendTo(layersMain);this.layerTools=new Component('bottomMenu','layers-control');this.layerTools.appendTo(layersMain);this.layerTools.setHeight('1');this.layerTools.addButton('function','layers-add','mdi-plus');this.layerTools.addButton('function','layers-up','mdi-arrow-up');this.layerTools.addButton('function','layers-down','mdi-arrow-down');this.layerTools.addButton('function','layers-duplicate','mdi-content-duplicate');this.layerTools.addButton('function','layers-delete','mdi-delete');artboardMain.activateGizmos()}
LayersPanel.prototype.initArtboardPanel=function(artboardMain){let content=new Component('contentBox');content.appendTo(artboardMain);let subtitle=new Component('titleBarBare');subtitle.addTitle('RESIZE SPRITE');subtitle.appendTo(content);let frame=new Component('frame');frame.appendTo(content);frame.setHeight('2');let anchorBox=new Component('idBox','artboard-anchor');anchorBox.appendTo(frame);let block=[];for(let i=0;i<9;i++){let span=document.createElement('span');block.push(document.createElement('div'));block[i].appendChild(span);block[i].setAttribute('data-anchor',i);anchorBox.DOM.appendChild(block[i]);let _this=this;block[i].addEventListener('click',function(e){let blk=e.currentTarget,n=blk.dataset.anchor;_this.artboard.anchor=setAnchor(n)},!1)}
this.artboard.anchor=setAnchor(4);function setAnchor(posIndex){var icons=['mdi mdi-arrow-top-left','mdi mdi-arrow-up','mdi mdi-arrow-top-right','mdi mdi-arrow-left','mdi mdi-square','mdi mdi-arrow-right','mdi mdi-arrow-bottom-left','mdi mdi-arrow-down','mdi mdi-arrow-bottom-right',],offset=4-posIndex,posRow=Math.floor(posIndex/3),posCol=posIndex-(posRow*3),skipCol=-1;if(posCol==2)skipCol=0;if(posCol==0)skipCol=2;for(let i=0;i<9;i++){let blockRow=Math.floor(i/3),blockCol=i-(blockRow*3);block[i].removeAttribute('data-active');let span=block[i].firstChild;if(i+offset>=0&&blockCol!=skipCol){span.className=icons[i+offset]}
else span.className=''}
block[posIndex].setAttribute('data-active','');return[posCol,posRow]}
let sizeBox=new Component('idBox','artboard-size');sizeBox.appendTo(frame);this.artboard.ui.w=sizeBox.addGizmo('numberDrag','art-width',this.artboard.width,'WIDTH',setWidth.bind(this));this.artboard.ui.w.setFormat('number',1,480);function setWidth(val){this.artboard.width=val}
this.artboard.ui.h=sizeBox.addGizmo('numberDrag','art-height',this.artboard.height,'HEIGHT',setHeight.bind(this));this.artboard.ui.h.setFormat('number',1,480);function setHeight(val){this.artboard.height=val}
this.artboard.ui.w.pair.set(this.artboard.ui.h,'aspect');sizeBox.addButton('aspect','aspect-toggle','mdi-link').toggle(this.artboard.aspectLock,'mdi-link-off');var wBox=this.artboard.ui.w;sizeBox.mapButtons({'aspect-toggle':function(){wBox.pair.toggle()}});content.addButton('cta','art-resize','RESIZE');let gridGuides=new Component('idBox','artboard-grids');gridGuides.appendTo(content);subtitle=new Component('titleBarBare');subtitle.addTitle('GRIDS & GUIDES');subtitle.appendTo(gridGuides);frame=new Component('frame');frame.appendTo(gridGuides);frame.setHeight('2');this.artboard.ui.hud=new Component('classBox','toggles');this.artboard.ui.hud.appendTo(frame);this.artboard.ui.hud.addButton('check','art-toggle-grid','SHOW GRID').toggle(this.settings.showGrid);this.artboard.ui.hud.addButton('check','art-toggle-guide','SHOW GUIDES').toggle(this.settings.showGuides);content.addButton('cta','art-guides-clear','CLEAR ALL');let bgChoice=new Component('idBox','artboard-bg');bgChoice.appendTo(content);subtitle=new Component('titleBarBare');subtitle.addTitle('BACKGROUND');subtitle.appendTo(bgChoice);frame=new Component('frame');frame.appendTo(bgChoice);frame.setHeight('2');let bg=['light','dark','color','image',];for(let i=0;i<4;i++){let swatchBox=document.createElement('section');swatchBox.className='swatch';frame.DOM.appendChild(swatchBox);let newSwatch=document.createElement('div'),swatchTitle=document.createElement('div');newSwatch.className='preset options';newSwatch.setAttribute('data-preset',bg[i]);swatchTitle.innerHTML=bg[i];swatchBox.appendChild(newSwatch);swatchBox.appendChild(swatchTitle)}
this.artboardTools=content}
LayersPanel.prototype.updateArtboardPanel=function(w,h){this.width=w;this.height=h;this.ui.w.valueDOM.value=w;this.ui.h.valueDOM.value=h}
LayersPanel.prototype.addLayerCard=function(layerId,title,visible){this.card[layerId]=new Component('card',layerId);let card=this.card[layerId];card.appendTo('#layers-cards');card.setHeight('4');let canvas=document.createElement('canvas');canvas.width=this.thumbSize;canvas.height=this.thumbSize;card.DOM.appendChild(canvas);card.addTitle(title).editable(sprite.layerProps(layerId),'name');card.addButton('function','layers-visible','mdi-eye').toggle(visible,'mdi-eye-off');this.setActiveCard(layerId);return this.card[layerId]}
LayersPanel.prototype.deleteLayerCard=function(layerId){let layerCard=this.getLayerCard(layerId),parent=layerCard.parentNode;parent.removeChild(layerCard)}
LayersPanel.prototype.deleteAllLayerCards=function(layerId){let parent=document.getElementById('layers-cards');while(parent.firstChild){parent.removeChild(parent.firstChild)}}
LayersPanel.prototype.updateCard=function(layerId,objProps){}
LayersPanel.prototype.setActiveCard=function(layerId){let thumbs=document.getElementsByClassName('card');for(let i=0;i<thumbs.length;i++){thumbs[i].removeAttribute('data-active');let cardId=thumbs[i].getAttribute('data-card');this.card[cardId].setHeight('4');if(cardId==layerId){thumbs[i].setAttribute('data-active','');this.card[cardId].setHeight('5');this.thumb=thumbs[i].firstChild}}}
LayersPanel.prototype.getLayerCard=function(layerId){let thumbs=document.getElementsByClassName('card');for(let i=0;i<thumbs.length;i++){let cardId=thumbs[i].getAttribute('data-card');if(cardId==layerId){return thumbs[i]}}}