FramesPanel=function(){this.thumbSize=65;this.title="TIMELINE";this.titleDOM;this.panelMenu;this.frameTools;this.minimap;this.viewfinder;this.viewMask;this.player={fps:12,play:!1,loop:{},timeStamp:(new Date).getTime(),frame:1,sprite:{}};this.onionSkinGizmo;this.onionSkinUpdate=function(){};this.style={hColor:window.getComputedStyle(document.documentElement).getPropertyValue("--ui-color-orange")}};
FramesPanel.prototype.init=function(){var c=new Component("panel","panel-frames");c.appendTo("#app-main");var b=new Component("panel","frames-preview");b.setHeight("4");b.appendTo(c);var a=new Component("titleBar");a.setHeight("4");a.addTitle("PREVIEW");a.appendTo(b);a.addGizmo("numberDrag","set-fps",12,"FPS",function(a){this.player.fps=a;this.player.sprite.fps=a;this.player.play=0==this.player.fps?!1:!0}.bind(this));a.gizmo["set-fps"].setFormat("number",0,60);a=new Component("subPanel","frames-minimap");
a.appendTo(b);this.createMinimap(a.DOM);this.updateViewfinder(0,0,0,0);a=new Component("panel","frames-mainpanel");a.appendTo(c);this.panelMenu=new Component("topMenu");this.panelMenu.appendTo(a);b=new Component("subPanel","frames-timeline");b.appendTo(a);b.setHeight("3");this.panelMenu.addButton("tab","frames-preview","mdi-movie").toggleMenu(!0);this.panelMenu.addButton("tab","frames-timeline","mdi-animation").toggleMenu(!0);this.panelMenu.button["frames-timeline"].toggleTab=!1;this.panelMenu.button["frames-timeline"].toggleSelf=
!1;this.panelMenu.addButton("function","frames-onionskin","mdi-checkbox-multiple-blank-circle-outline").toggle();this.titleDOM=new Component("titleBarThin");this.titleDOM.addTitle(this.title);this.titleDOM.appendTo(b);this.onionSkinGizmo=this.titleDOM.addGizmo("numberDrag","set-onionskin",0,"ONIONSKIN",function(a){this.onionSkinUpdate(a)}.bind(this));this.onionSkinGizmo.drag.setDirection("y");a=new Component("contentBox","frames-thumbs");a.setHeight("2");a.appendTo(b);this.frameTools=new Component("bottomMenu",
"frames-control");this.frameTools.appendTo(b);this.frameTools.setHeight("1");this.frameTools.addButton("function","frames-add","mdi-plus");this.frameTools.addButton("function","frames-left","mdi-arrow-left");this.frameTools.addButton("function","frames-right","mdi-arrow-right");this.frameTools.addButton("function","frames-duplicate","mdi-content-duplicate");this.frameTools.addButton("function","frames-delete","mdi-delete");this.frameTools.addButton("cta","frames-export","EXPORT");c.activateGizmos()};
FramesPanel.prototype.getPanelHeight=function(){var c=document.getElementById("frames-timeline"),b=c.offsetHeight||0;"none"==c.style.display&&(b=0);return b};
FramesPanel.prototype.createMinimap=function(c){this.minimap=document.createElement("canvas");this.minimap.id="minimap";this.minimap.width=c.offsetWidth;this.minimap.height=c.offsetWidth;this.minimap.getContext("2d").imageSmoothingEnabled=!1;c.appendChild(this.minimap);this.viewMask=document.createElement("div");this.viewMask.className="player-mask";c.appendChild(this.viewMask);var b=document.createElement("div"),a=document.createElement("span");b.className="player";a.className="mdi mdi-play";b.appendChild(a);
c.appendChild(b);c.addEventListener(pointerEvent.click,function(){this.player.play?(this.player.play=!1,a.className="mdi mdi-pause",b.className="player pause",this.highlightThumbFrameNum(0)):(this.player.play=!0,a.className="mdi mdi-play",b.className="player play")}.bind(this),!1);var d=document.createElement("div"),e=document.createElement("span");d.className="player-icon-sml";e.className="mdi mdi-play-pause";d.appendChild(e);c.appendChild(d)};
FramesPanel.prototype.updateMinimap=function(c,b){var a=this.minimap.getContext("2d"),d=this.minimap.width,e=this.minimap.height,f=c.mixdown,g=this.viewfinder,h=this.viewMask,n=g.pw,p=g.ph,k=g.px,q=g.py,l=Math.round(e-g.vh-g.vy),r=0>k+g.vx?0:k+g.vx,m=Math.round(d-g.vx-g.vw-k);h.style.borderTop=(0>g.vy?0:g.vy)+"px solid rgba(0,0,0,.4)";h.style.borderBottom=(0>l?0:l)+"px solid rgba(0,0,0,.4)";h.style.borderLeft=r+"px solid rgba(0,0,0,.4)";h.style.borderRight=(0>m?0:m)+"px solid rgba(0,0,0,.4)";if(!this.player.play||
b)a.globalAlpha=1,a.clearRect(0,0,d,e),a.imageSmoothingEnabled=!1,a.drawImage(f,0,0,f.width,f.height,k,q,n,p),a.strokeRect(0,0,150,150)};FramesPanel.prototype.updateViewfinder=function(c,b,a,d,e,f,g,h){this.viewfinder={vx:c,vy:b,vw:a,vh:d,px:e,py:f,pw:g,ph:h}};
FramesPanel.prototype.addThumb=function(c,b){for(var a=document.getElementsByClassName("frameThumb"),d=0;d<a.length;d++){a[d].removeAttribute("data-active");var e=parseInt(a[d].getAttribute("data-frame-num"));e>=c&&(e++,a[d].setAttribute("data-frame-num",e),a[d].style.order=e,a[d].childNodes[1].innerHTML=e)}d=document.getElementById("frames-thumbs");var f=document.createElement("div");e=document.createElement("canvas");var g=document.createElement("div");f.setAttribute("data-frame-num",c);f.className=
"frameThumb";f.style.order=c;f.style.width=this.thumbSize+"px";f.style.height=this.thumbSize+"px";d.appendChild(f);e.width=this.thumbSize;e.height=this.thumbSize;e.getContext("2d").imageSmoothingEnabled=!1;f.appendChild(e);g.className="fnumber";g.innerHTML=c;f.appendChild(g);f.setAttribute("data-active","");this.titleDOM.title[0].DOM.innerHTML=this.title+" ("+c+"/"+a.length+")";f.addEventListener(pointerEvent.click,function(a){a=f.getAttribute("data-frame-num");this.selectThumb(a);b(a)}.bind(this),
!1)};FramesPanel.prototype.selectThumb=function(c){for(var b=document.getElementsByClassName("frameThumb"),a=0;a<b.length;a++)b[a].getAttribute("data-frame-num")==c?b[a].setAttribute("data-active",""):b[a].removeAttribute("data-active");this.titleDOM.title[0].DOM.innerHTML=this.title+" ("+c+"/"+b.length+")"};
FramesPanel.prototype.updateThumb=function(c){for(var b=c.mixdown,a=document.getElementsByClassName("frameThumb"),d=0;d<a.length;d++){var e=a[d],f=e.firstChild;if(e.getAttribute("data-frame-num")==c.num){c=f.getContext("2d");c.clearRect(0,0,f.width,f.height);c.drawImage(b,0,0,b.width,b.height,0,0,f.width,f.height);break}}};
FramesPanel.prototype.updateAllThumbs=function(c){for(var b=document.getElementsByClassName("frameThumb"),a=0;a<c.length;a++){var d=c[a],e=d.mixdown,f=b[a],g=f.firstChild;f.childNodes[1].innerHTML=d.num;f.setAttribute("data-frame-num",d.num);f.style.order=d.num;d=g.getContext("2d");d.clearRect(0,0,g.width,g.height);d.drawImage(e,0,0,e.width,e.height,0,0,g.width,g.height)}};
FramesPanel.prototype.playPreview=function(c){this.player.play=!0;this.player.sprite=c||this.player.sprite;var b=this;(function d(){var c=1E3/b.player.fps,f=(new Date).getTime(),g=f-b.player.timeStamp;g>c&&(b.player.timeStamp=f-g%c,b.player.play&&b.playFrame());b.player.loop=requestAnimationFrame(d)})()};
FramesPanel.prototype.playFrame=function(){if(this.player.play){var c=this.player.sprite,b=c.frameData.length,a=this.player.frame;c=c.getFrameData(a);this.updateMinimap(c,!0);this.highlightThumbFrameNum(a);parseInt(a)==b?this.player.frame=1:this.player.frame++}};FramesPanel.prototype.stopPreview=function(){this.player.play=!1;this.player.frame=1};
FramesPanel.prototype.highlightThumbFrameNum=function(c){for(var b=document.getElementsByClassName("frameThumb"),a=0;a<b.length;a++)b[a].getAttribute("data-frame-num")==c?(b[a].childNodes[1].style.backgroundColor=this.style.hColor,b[a].childNodes[1].style.color="white"):(b[a].childNodes[1].style.backgroundColor="",b[a].childNodes[1].style.color="")};FramesPanel.prototype.removeAllThumbs=function(){for(var c=document.getElementById("frames-thumbs");c.firstChild;)c.removeChild(c.firstChild)};
FramesPanel.prototype.removeThumb=function(c){var b=document.getElementsByClassName("frameThumb"),a=document.getElementById("frames-thumbs");if(1!=b.length){for(var d=0;d<b.length;d++)parseInt(b[d].getAttribute("data-frame-num"))==c&&a.removeChild(b[d]);for(a=0;a<b.length;a++){d=b[a];var e=parseInt(d.getAttribute("data-frame-num"));e>c&&(e--,d.setAttribute("data-frame-num",e),d.style.order=e,d.childNodes[1].innerHTML=e);e==c&&d.setAttribute("data-active","");c==b.length+1&&e==b.length&&(d.setAttribute("data-active",
""),c=e)}this.titleDOM.title[0].DOM.innerHTML=this.title+" ("+c+"/"+b.length+")";this.player.frame=1}};